name: 游 Verkbei칧ni
description: 칍skir eftir n칳jum eiginleika e칧a endurb칩t
title: "[VERKBEI칋NI]: "
labels: ["verkbei칧ni", "쬬rf a칧 sko칧a"]
body:
  - type: markdown
    attributes:
      value: |
        Takk fyrir a칧 leggja til endurb칩t! Vinsamlegast fylltu 칰t 쬰tta form.

  - type: dropdown
    id: verkefni
    attributes:
      label: Verkefni
      description: Hva칧a verkefni sn칳r 쬰tta a칧?
      options:
        - BORG kerfi칧
        - AI Stefna
        - Scite innlei칧ing
        - Arctic Tracker
        - Temjum T칝knina
        - Anna칧
      default: 0
    validations:
      required: true

  - type: textarea
    id: lysing
    attributes:
      label: L칳sing 치 verkbei칧ni
      description: Hva칧 vilt 쮂 a칧 ver칧i gert?
      placeholder: L칳stu hva칧 쮂 vilt sj치...
    validations:
      required: true

  - type: textarea
    id: rokin
    attributes:
      label: R칬k fyrir verkbei칧ni
      description: Af hverju er 쬰ssi breyting gagnleg?
      placeholder: 칔tsk칳r칧u hvers vegna 쬰tta er mikilv칝gt...
    validations:
      required: true

  - type: dropdown
    id: forgangur
    attributes:
      label: Forgangur
      description: Hversu mikilv칝g er 쬰ssi verkbei칧ni?
      options:
        - L치gur
        - Mi칧lungsur
        - H치r
        - Mj칬g h치r
      default: 1
    validations:
      required: true
